GET http://localhost:5000/games

###
POST http://localhost:5000/games
Content-Type: application/json

{
	"name": "Mega Man 7"
}

###
PUT http://localhost:5000/games/61783cfef54821f9ec20cfaf
Content-Type: application/json

{
	"name": "Mega Man 3"
}

###
DELETE http://localhost:5000/games/6178431a0f93e4f1f77ea1a2