GET http://localhost:5000/games

###
POST http://localhost:5000/games
Content-Type: application/json

{
	"name": "Mega Man 7"
}

###
DELETE http://localhost:5000/games/6178431a0f93e4f1f77ea1a2